### ISSUE TITLE
re: addons config pickle

### ISSUE THREAD

**Issue by meta-androcto** [qwenger/BAddons#1]
hi, I'm very interested in your addons installer, does it work with the pickle file not serialized?
What I would like to do is use for my AF series of addons here: https://github.com/meta-androcto/blenderpython/tree/master/scripts/addons_extern
however I'm not that good with compiled code as such, would it work the same with uncompiled code ( in text form?) I'm trying to put together package of addons for 2.78 release & your system is the best. I can do individual files & zips, but this is not optimal. Thanks for any information,
Note: this is separate project for addons & not part of blender cloud addon.
Thanks again.
Brendon.

**Comment by qwenger** [comment]
Hi Brendon,
Thanks for your interest and sorry to have overlooked your post until now.

I actually have to update my addon manager and probably to enhance/modify it a bit.
To answer your question, well Pickle in protocol version 4 uses serialized/byte representation. This is nothing to be changed (maybe protocol version 1 would use plain text, but I'm not sure it is worth it)...
What I would - and probably will at some point - do is using JSON instead of Pickle. It is much more common for simple info exchange over the Internet and also human-readable, which is not always bad... Plus it would allow other users to develop their own addons based on my collection in a more convenient way.

So - you are welcome to inspirating yourself from my system, but I would _not_ use it directly, at least not until I have enhanced it. And if you search for a simple text exchange format (with no custom Python objects needed), my advice would be to go for JSON.

Hope this answers your question.

Best,
Matpi
